<?php

namespace MailPoetVendor;

// autoload.php @generated by Composer
require_once __DIR__ . '/composer/autoload_real.php';
return \MailPoetVendor\ComposerAutoloaderInit10f40c20988b71420f804b4d3c8110d6::getLoader();
